apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    path: db
    repoURL: https://github.com/Iwandoin/todo-helm.git
    helm:
      valueFiles:
        - db_values.yml
    targetRevision: HEAD