apiVersion: v1
kind: Service
metadata:
  name: {{ include "front.fullname" . }}
  labels:
    app:
      {{ .Values.service.label }}
spec:
  clusterIP: {{ .Values.service.ip }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app:
      {{ .Values.service.label }}
